services:
  bot:
    build: .
    env_file:
      - .env
    ports:
      - "${METRICS_BIND_IP:-127.0.0.1}:${METRICS_PORT:-9090}:9090"
    restart: unless-stopped
    depends_on:
      - pot-provider

  pot-provider:
    build:
      context: https://github.com/Brainicism/bgutil-ytdlp-pot-provider.git
    restart: unless-stopped
